### ISSUE TITLE
currently unable to download due to CRC issue

### ISSUE THREAD

**Issue by kotter** [ArduCAM/ArduCAM_ESP32S_UNO#17]
Unable to properly download due to a bad CRC return.  I have tried this on Mac/Windows/Linux, all end up with the same results:

![CRC](https://user-images.githubusercontent.com/1143413/54698274-67ce3e00-4b05-11e9-9aa0-391c7a32d807.PNG)

Is there any way to work around this issue?  seems like anywhere I see it, it just "magically" works, but I'm on 2 days of attempting anything to get this going, and no luck.

**Comment by swaxolez** [comment]
Same problem here.  Just tried on a mac

**Comment by IngmarG** [comment]
Same here
.

**Comment by UCTRONICS** [comment]
@swaxolez @IngmarG 
We have updated the library today, Please try it again.

**Comment by IngmarG** [comment]
No joy. Same issue. My Arduino version is 1.8.8.

 This is my log output:

 Error downloading https://github.com/arducam/ArduCAM_ESP32S_UNO/raw/master/package/release/download/ArduCAM_ESP32S_UNO.zip
java.lang.RuntimeException: java.lang.Exception: Error downloading https://github.com/arducam/ArduCAM_ESP32S_UNO/raw/master/package/release/download/ArduCAM_ESP32S_UNO.zip
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading https://github.com/arducam/ArduCAM_ESP32S_UNO/raw/master/package/release/download/ArduCAM_ESP32S_UNO.zip
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:139)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:73)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:55)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:101)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 416
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:205)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:132)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:137)
	... 5 more

**Comment by MateuszZiolek** [comment]
Yep and still same
` Error downloading https://github.com/ArduCAM/ArduCAM_ESP8266_UNO/raw/master/releases/download/2.2.4/ArduCAM_ESP8266_UNO.zip
java.lang.RuntimeException: java.lang.Exception: Error downloading https://github.com/ArduCAM/ArduCAM_ESP8266_UNO/raw/master/releases/download/2.2.4/ArduCAM_ESP8266_UNO.zip
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading https://github.com/ArduCAM/ArduCAM_ESP8266_UNO/raw/master/releases/download/2.2.4/ArduCAM_ESP8266_UNO.zip
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:139)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:73)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:55)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:101)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 416
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:205)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:132)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:137)
	... 5 more
`

**Comment by tmckenna-1** [comment]
I am having the same issue on Windows.
